# revision 21191
# category Package
# catalog-ctan /info/examples/tabulars-e
# catalog-date 2011-01-24 16:14:35 +0100
# catalog-license lppl
# catalog-version 1.0
Name:		texlive-tabulars-e
Version:	1.0
Release:	5
Summary:	Examples from the book "Typesetting tables with LaTeX"
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/info/examples/tabulars-e
License:	LPPL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/tabulars-e.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/tabulars-e.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg

%description
The bundle presents the examples of the book "Typesetting
tables with LaTeX" (ISBN 978-1-906860-25-7), as standalone
documents.

#-----------------------------------------------------------------------
%files
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-1.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-14.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-15.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-16.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-17.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-18.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-19.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-01-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-1.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/01-02-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-14.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-15.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-16.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-17.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-18.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-01-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-14.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-15.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-11.ltx2crop
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-04-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-05-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-06-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-06-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-06-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-06-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-07-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-07-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-07-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-07-4.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-07-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-08-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-09-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-09-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-09-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-10-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-11-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-12-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-12-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-13-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-13-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-13-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-13-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-14.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-15.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-14-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-15-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-15-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-15-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-16-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-16-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-16-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-17-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-17-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-17-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-17-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-17-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-18-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-18-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-18-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-18-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-18-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-19-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-19-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-20-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-20-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-20-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-20-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-21-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-21-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-21-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-21-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-22-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-22-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-22-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-22-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-23-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-23-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-23-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-23-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-24-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-24-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-24-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-24-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-25-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-26-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-27-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-27-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-27-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-27-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-28-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-28-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-28-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-28-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/02-29-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-01-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-02-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-03-3.ltxb
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/03-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-10.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-11.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-12.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-13.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-14.ltx1
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-15.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-3.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-4.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-5.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-8.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-01-9.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-02-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-02-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-03-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-03-3.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-04-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-04-3.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-04-4.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-04-5.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-3.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-4.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-5.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-6.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-7.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-05-8.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-3.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-4.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-5.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-6.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-7.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-8.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/04-06-9.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-04-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-04-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-06-1.ltxE
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-06-2.ltxE
%doc %{_texmfdistdir}/doc/latex/tabulars-e/05-06-3.ltxE
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-1.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-10.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-11.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-12.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-13.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-14.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-15.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-16.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-17.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-18.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-19.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-2.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-20.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-21.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-22.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-23.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-24.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-25.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-26.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-27.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-28.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-29.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-3.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-30.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-31.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-32.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-33.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-34.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-35.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-36.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-37.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-38.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-39.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-4.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-40.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-41.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-42.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-43.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-44.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-45.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-46.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-5.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-6.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-7.ltxps
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-8.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/06-00-9.ltx
%doc %{_texmfdistdir}/doc/latex/tabulars-e/07-02-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/07-02-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/07-03-1.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/07-03-2.ltx2
%doc %{_texmfdistdir}/doc/latex/tabulars-e/README
%doc %{_texmfdistdir}/doc/latex/tabulars-e/din8.eps

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar doc %{buildroot}%{_texmfdistdir}


%changelog
* Wed Jan 04 2012 Paulo Andrade <pcpa@mandriva.com.br> 1.0-2
+ Revision: 756500
- Rebuild to reduce used resources

* Sat Nov 05 2011 Paulo Andrade <pcpa@mandriva.com.br> 1.0-1
+ Revision: 719648
- texlive-tabulars-e
- texlive-tabulars-e
- texlive-tabulars-e

